### PR TITLE
fix(ssr): simplify noExternal in dev

### LINKED ISSUE #168: vite-plugin-svelte 1.0.0-next.23 breaks the ssr with svelte-i18n
### Describe the bug

When I update my SvelteKit App to vite-plugin-svelte 1.0.0-next.23 it will cause error:
```
9:44:24 PM [vite] Error when evaluating SSR module /node_modules/.pnpm/svelte-i18n@3.3.10_svelte@3.42.4/node_modules/svelte-i18n/dist/runtime.esm.js:
SyntaxError: Illegal property in declaration context
    at new AsyncFunction (<anonymous>)
    at instantiateModule (/home/www/sources/node_modules/.pnpm/vite@2.5.6/node_modules/vite/dist/node/chunks/dep-9f74b403.js:75099:28)
```

Only revert back to 1.0.0-next.22 of this module makes everything works again.

### Reproduction

Use svelte-i18n with SSR.

### Logs

_No response_

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (2) x64 DO-Regular
    Memory: 291.61 MB / 3.84 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.6 - /usr/bin/node
    npm: 6.14.15 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.46 => 1.0.0-next.46 
    @sveltejs/adapter-static: ^1.0.0-next.18 => 1.0.0-next.18 
    @sveltejs/kit: next => 1.0.0-next.166 
    svelte: ^3.42.5 => 3.42.5
```

### Severity

blocking all usage of vite-plugin-svelte

### PR DESCRIPTION
**Pull request by bluwy**
Fixes #168 

There isn't any reason to add Svelte JS libraries to `ssr.noExternal` in dev mode since `svelte/ssr` isn't handled there too, so this change removes it.

### CODE REVIEW

**Review by dominikg — APPROVED** [review]

File: packages/vite-plugin-svelte/src/utils/options.ts [hunk 1]
```diff
@@ -199,14 +200,23 @@ export function buildExtraViteConfig(
...
 
+	// for ssr build, we include all svelte deps to resolve `svelte/ssr`.
+	// for other cases, we can ignore `svelte/ssr` as it would make development faster
+	// and also because vite doesn't handle them properly.
+	// see https://github.com/sveltejs/vite-plugin-svelte/issues/168
+	// see https://github.com/vitejs/vite/issues/2579
 	// @ts-ignore
-	extraViteConfig.ssr = buildSSROptionsForSvelte(svelteDeps, options, config);
+	extraViteConfig.ssr = buildSSROptionsForSvelte(
+		options.isBuild && config.build?.ssr ? svelteDeps : svelteComponentLibDeps,
```
Comment (dominikg) [inline packages/vite-plugin-svelte/src/utils/options.ts:216]: should this be moved into the build function? it gets the options passed in and also checks isBuild  and SSR internally.

the way it is now, its a bit harder to grasp what's added exactly BC the input varies

**Review by dominikg — APPROVED** [review]
