### PR TITLE
fix: only apply infix filter to basename

### LINKED ISSUE #919: Infix logic should only apply to basename
### Describe the bug

The infix logic for allowing `*.svelte.*` files (e.g. `thing.svelte.test.js`) to be processed by Svelte fails when the directory contains the infix, for example because the project name is `learn.svelte.dev`. It should only apply to the basename

### Reproduction URL

N/A (will PR, one sec)

### Reproduction

_No response_

### Logs

_No response_

### System Info

```shell
next
```

### PR DESCRIPTION
**Pull request by Rich-Harris**
fixes #919

### CODE REVIEW

File: packages/vite-plugin-svelte/src/utils/id.js [hunk 1]
```diff
@@ -179,10 +180,15 @@ function buildFilter(include, exclude, extensions) {
...
-		rollupFilter(filename) &&
-		infixes.some((infix) => filename.includes(infix)) &&
-		extensions.some((ext) => filename.endsWith(ext));
+	return (filename) => {
+		const basename = path.basename(filename);
+
+		return (
+			rollupFilter(filename) &&
+			infixes.some((infix) => basename.includes(infix)) &&
+			extensions.some((ext) => filename.endsWith(ext))
```
Comment (dummdidumm) [inline packages/vite-plugin-svelte/src/utils/id.js:189]: Isn't it better to also use the basename here? Where would that return a false negative?
```suggestion
			extensions.some((ext) => basename.endsWith(ext))
```

Comment (Rich-Harris) [reply packages/vite-plugin-svelte/src/utils/id.js:189]: Identical result, which is why I didn't bother changing it. But certainly no harm in it

**Review by bluwy — APPROVED** [review]
