### PR TITLE
fix(inspector): disable while combo is held when extra key are pressed or leaving browser

### LINKED ISSUE #557: svelte-inspector interfering with OS screenshot shortcuts
### Describe the bug

I frequently take screenshots, which on macOS is done using `cmd+shift+3/4`. When I do that, the inspector shows up and photobombs my screenshot, then it stays active afterwards.

It's a bit disorienting to me because after pressing `cmd+shift+4` I now need to remember to do a separate shortcut to hide the inspector (I found myself trying `Escape` a lot).

https://user-images.githubusercontent.com/11315492/208026596-05fc8dff-6d07-4b08-9c8f-f699fd37ecd5.mp4

### Reproduction URL

Not applicable here imo

### Reproduction

1. `npm create svelte`
2. Enable `inspector` in `svelte.config.js`:
```js
  vitePlugin: {
    experimental: {
      inspector: true,
    },
  },
```
3. `npm i && npm run dev`
4. Take a screenshot using `cmd+shift+4`

### Logs

_No response_

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 1.23 GB / 32.00 GB
    Shell: 3.5.1 - /usr/local/bin/fish
  Binaries:
    Yarn: 3.3.0 - ~/Library/Application Support/Volta/tools/image/yarn/3.3.0/bin/yarn
    npm: 8.19.2 - ~/Library/Application Support/Volta/tools/image/node/18.12.1/bin/npm
  Browsers:
    Brave Browser: 108.1.46.134
    Chrome: 108.0.5359.124
    Firefox: 107.0
    Firefox Developer Edition: 108.0
    Safari: 15.6.1
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0 
    @sveltejs/kit: ^1.0.0 => 1.0.0 
    svelte: ^3.54.0 => 3.55.0 
    vite: ^4.0.0 => 4.0.1
```

### PR DESCRIPTION
**Pull request by dominikg**
reduces occurrences of #557

### CODE REVIEW

File: packages/vite-plugin-svelte-inspector/src/runtime/Inspector.svelte [hunk 1]
```diff
@@ -145,7 +145,11 @@
 	}
 
 	function is_combo(event) {
-		return toggle_combo?.every((key) => is_key_active(key, event));
+		return is_toggle(event) && toggle_combo?.every((key) => is_key_active(key, event));
```
Comment (dominikg) [inline packages/vite-plugin-svelte-inspector/src/runtime/Inspector.svelte:148]: ctrl-shift-X  returns false for is_combo now, previously it would return true

File: packages/vite-plugin-svelte-inspector/src/runtime/Inspector.svelte [hunk 2]
```diff
@@ -167,14 +171,13 @@
 	}
 
 	function keydown(event) {
-		if (event.repeat || event.key == null) {
+		if (event.repeat || event.key == null || (!enabled && !is_toggle(event))) {
```
Comment (dominikg) [inline packages/vite-plugin-svelte-inspector/src/runtime/Inspector.svelte:174]: return early when disabled and the key isn't a toggle

File: packages/vite-plugin-svelte-inspector/src/runtime/Inspector.svelte [hunk 3]
```diff
@@ -267,7 +274,8 @@
 	}
 
 	function onLeave() {
-		if (hasOpened) {
+		// disable if a file has been opened or combo is held
+		if (enabled && (has_opened || hold_start_ts)) {
```
Comment (dominikg) [inline packages/vite-plugin-svelte-inspector/src/runtime/Inspector.svelte:278]: this helps with shortcuts that unfocus the browser window, eg ctrl-shift-print

**Review by bluwy — APPROVED** [review]
